source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               schema/,\
               .options,\
               lib/,\
               lib/mcp-annotations-0.5.1.jar,\
               lib/mcp-core-0.14.0.jar,\
               lib/mcp-json-jackson2-0.14.0.jar,\
               
